### ISSUE TITLE
boba compile fails on python 3.8.2

### ISSUE THREAD

**Issue by AmethystGear** [uwdata/multiverse-spec#8]
using the boba compile command fails when using python 3.8.2 but succeeds when using python 3.7.5.
to test this, I used `pyenv`
here is the output from running boba compile in the /example/simple/ directory when using python 3.8.2:
```
Creating multiverse from ./template.py
Traceback (most recent call last):
  File "/home/shiven/.local/bin/boba", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shiven/.local/lib/python3.8/site-packages/boba/cli.py", line 29, in compile
    ps.main()
  File "/home/shiven/.local/lib/python3.8/site-packages/boba/parser.py", line 394, in main
    self._write_server_config()
  File "/home/shiven/.local/lib/python3.8/site-packages/boba/parser.py", line 334, in _write_server_config
    self.adg.create(self.code_parser.blocks)
  File "/home/shiven/.local/lib/python3.8/site-packages/boba/adg.py", line 211, in create
    self._merge()
  File "/home/shiven/.local/lib/python3.8/site-packages/boba/adg.py", line 87, in _merge
    for g in gp:
RuntimeError: dictionary keys changed during iteration
```

**Comment by AmethystGear** [comment]
turns out, this had a very simple fix! fixed by #16
